apiVersion: 1

datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    orgId: 1
    url: timescaledb:5432
    database: energy_monitoring
    user: energy
    secureJsonData:
      password: energy
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
    isDefault: true
    editable: true
